### ISSUE TITLE
Not for remote server migrations?

### ISSUE THREAD

**Issue by Dracozny** [CobayeGunther/Emby2Jelly#15]
so I ran this from my own PC given the layout of the settings.ini file. but in either case Jelly is running on new hardware running on Ubuntu, and Emby is running on an older server inside of a truenas jail. 
It seems to pull user data from Emby just fine but then crashes. 

`##### EmbySync Done #####

Traceback (most recent call last):
  File "APImain.py", line 500, in <module>
    jelly(newUser_pw)
  File "APImain.py", line 415, in jelly
    jellyUsers = jelly_get_users_list()
  File "APImain.py", line 187, in jelly_get_users_list
    return "error : " + json.loads(response.content.decode('utf-8'))
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`

I noticed this issue which appeared somewhat similar hence the title https://github.com/CobayeGunther/Emby2Jelly/issues/8#issuecomment-735010918

**Comment by Dracozny** [comment]
I figured it out already. Issue was Jellyfin was not using the trailing /jellyfin/ after.
