### ISSUE TITLE
KeyError: 'Name'

### ISSUE THREAD

**Issue by Haplo164** [CobayeGunther/Emby2Jelly#16]
I'm getting an error on the first user while copying watched data.
```
Traceback (most recent call last):
  File "/home/example/Workspace/Emby2Jelly/APImain.py", line 500, in <module>
    jelly(newUser_pw)
  File "/home/example/Workspace/Emby2Jelly/APImain.py", line 421, in jelly
    iterateMigrationData()
  File "/home/example/Workspace/Emby2Jelly/APImain.py", line 363, in iterateMigrationData
    MigrationMedia['JellyId'] = search_byName(MigrationMedia,Library)
  File "/home/example/Workspace/Emby2Jelly/APImain.py", line 335, in search_byName
    if  jelly_movie['Name'] == MigrationMedia['Name']:
KeyError: 'Name'
```
if this is due to a missing or misidentified file on the jellyfin side I have no idea how to find it.

**Comment by ma-karai** [comment]
Same issue

**Comment by jkhsjdhjs** [comment]
This can be worked around by
```diff
diff --git a/APImain.py b/APImain.py
index bc63202..9c444b8 100644
--- a/APImain.py
+++ b/APImain.py
@@ -332,7 +332,7 @@ def jelly(newUser_pw):
        def search_byName(MigrationMedia,Library):
 
                for jelly_movie in Library['Items'] :
-                       if  jelly_movie['Name'] == MigrationMedia['Name']:
+                       if 'Name' in jelly_movie and 'Name' in MigrationMedia and jelly_movie['Name'] == MigrationMedia['Name']:
                                print("found by name {0}".format(jelly_movie['Name']))
                                return jelly_movie['Id']
                return None
```

**Comment by Unambiguous** [comment]
I had the same issue and needed to check the key at two places.

See: [Check key presence in item by Unambiguous · Pull Request #22 · Marc-Vieg/Emby2Jelly](https://github.com/Marc-Vieg/Emby2Jelly/pull/22)

**Comment by gbyrne2024** [comment]
> I had the same issue and needed to check the key at two places.
> 
> See: [Check key presence in item by Unambiguous · Pull Request #22 · Marc-Vieg/Emby2Jelly](https://github.com/Marc-Vieg/Emby2Jelly/pull/22)

That worked for me, cheers
