### ISSUE TITLE
jellyfin2emby

### ISSUE THREAD

**Issue by Killianbe** [CobayeGunther/Emby2Jelly#9]
Hi 
Anyway to Jellyfin2Emby ? 
thx

**Comment by Dracozny** [comment]
I would presume you already tried calling the Emby Server Jellyfin and vice versa...

**Comment by alphabitnz** [comment]
> I would presume you already tried calling the Emby Server Jellyfin and vice versa...

Yeah that doesn't work, even trying to back up jellyfin to file by placing its URL and key in the Emby fields gets an error
(works fine if the server is actually Emby)

```
(base) C:\Users\usernamehere\Downloads\Emby2Jelly-master>python APImain.py --tofile jellyfile
Migration to file jellyfile
Traceback (most recent call last):
  File "C:\Users\usernamehere\Downloads\Emby2Jelly-master\APImain.py", line 493, in <module>
    emby(selectedUsers)
  File "C:\Users\usernamehere\Downloads\Emby2Jelly-master\APImain.py", line 158, in emby
    users = emby_get_users_list(EMBY_APIKEY,EMBY_URLBASE,EMBY_HEADERS)
  File "C:\Users\usernamehere\Downloads\Emby2Jelly-master\APImain.py", line 102, in emby_get_users_list
    return "error : " + json.loads(response.content.decode('utf-8'))
  File "C:\Users\usernamehere\anaconda3\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\usernamehere\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\usernamehere\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by alphabitnz** [comment]
Update: managed to get it working after diagnosing the error above was just a 404.
Removing "jellyfin/" subdirectory from EMBY_URLBASE was all it took to get jellyfin backing up successfully
